// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okjhldurxlmtkirzgljn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ramhsZHVyeGxtdGtpcnpnbGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODM4MDYsImV4cCI6MjA3Mjk1OTgwNn0.x11yMBPVW2GGokUpBFrKMaoL3Ub8DE8PBArFbXrU-pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});